gservices:
  - type: web
    name: smartskill-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: BOT_TOKEN
        value: your-telegram-bot-token-here
